window:
  padding:
    x: 3
    y: 3

font:
  normal:
    family: Sarasa Term K
  size: 11

colors:
  primary:
    background: '#1d1f21'
    foreground: '#c5c8c6'
  cursor:
    cursor: '#c5c8c6'
  vi_mode_cursor:
    cursor: '#00ff00'
  selection:
    text: '#1d1f21'
    background: '#c5c8c6'
  normal:
    black: '#282a2e'
    red: '#a54242'
    green: '#8c9440'
    yellow: '#de935f'
    blue: '#5f819d'
    magenta: '#85678f'
    cyan: '#5e8d87'
    white: '#707880'
  bright:
    black: '#373b41'
    red: '#cc6666'
    green: '#b5bd68'
    yellow: '#f0c674'
    blue: '#81a2be'
    magenta: '#b294bb'
    cyan: '#8abeb7'
    white: '#c5c8c6'

cursor:
  vi_mode_style: Block
