[user]
name = "Ohjun Kwon"
email = "dev@kojandy.com"

[ui]
default-command = "log"
pager = "less -FRX"
merge-editor = "vimdiff"

[merge-tools.vimdiff]
program = "nvim"

[revsets]
log = "connected(ancestors(interests(), 2) | trunk())"

[revset-aliases]
"local()" = "(immutable_heads() | remote_branches()).."
"interests()" = "local() | trunk()..branches() | trunk()..@"

[templates]
log_node = '''
coalesce(
  if(!self, "◌"),
  if(root, "┴"),
  if(current_working_copy, if(pushed, "!", "@")),
  if(description.lower().starts_with("wip"), if(pushed, "▲", "△")),
  if(empty, if(pushed, "┿", "┼")),
  if(pushed, "●", "○"),
)
'''

[template-aliases]
"pushed" = "self.contained_in('::remote_branches()')"
"format_timestamp(timestamp)" = "timestamp.ago()"

[experimental-advance-branches]
enabled-branches = ["glob:wip/*"]
