[ui]
default-command = "log"
pager = "less -FRX"

[user]
name = "Ohjun Kwon"
email = "dev@kojandy.com"

[revsets]
log = "connected(ancestors(interests(), 2) | trunk())"

[revset-aliases]
"immutable_heads()" = "trunk() | tags() | remote_branches()"
"interests()" = "immutable_heads().. | trunk()..branches() | trunk()..@"
