#!/bin/sh
assert_exists() {
    if ! [ -x "$(command -v "$1")" ]; then
        echo "Error: $1 is not installed" >&2
        exit 1
    fi
}

assert_exists curl
assert_exists git
assert_exists python3
assert_exists vim
assert_exists zsh

./bin/dfm install zgen
./bin/dfm link
vim +PlugInstall +qall
zsh
