#!/bin/sh
[ -z "$DOTFILES" ] && echo "DOTFILES not set" && exit 1
[ -z "$XDG_CONFIG_HOME" ] && echo "XDG_CONFIG_HOME not set" && exit 1

ln -si "$DOTFILES/profile" ~/.profile

if [ -x "$(command -v vim)" ]; then
    ln -si "$DOTFILES/vim/vimrc" ~/.vimrc
fi

if [ -x "$(command -v zsh)" ]; then
    ln -si "$DOTFILES/zsh/zshrc" ~/.zshrc
fi

if [ -x "$(command -v tmux)" ]; then
    ln -si "$DOTFILES/tmux/tmux.conf" ~/.tmux.conf
fi

if [ -x "$(command -v git)" ]; then
    ln -si "$DOTFILES/git/gitconfig" ~/.gitconfig
    ln -si "$DOTFILES/git/gitignore_global" ~/.gitignore_global
fi

if [ -x "$(command -v Xorg)" ]; then
    ln -si "$DOTFILES/xorg/xprofile" ~/.xprofile
    ln -si "$DOTFILES/xorg/Xresources" ~/.Xresources
fi

if [ -x "$(command -v bspwm)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/bspwm"
    ln -si "$DOTFILES/bspwm/bspwmrc" "$XDG_CONFIG_HOME/bspwm/bspwmrc"
fi

if [ -x "$(command -v sxhkd)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/sxhkd"
    ln -si "$DOTFILES/sxhkd/sxhkdrc" "$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
fi

if [ -x "$(command -v compton)" ]; then
    ln -si "$DOTFILES/compton/compton.conf" ~/.compton.conf
fi

if [ -x "$(command -v polybar)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/polybar"
    ln -si "$DOTFILES/polybar/config" "$XDG_CONFIG_HOME/polybar/config"
    ln -si "$DOTFILES/polybar/launch.sh" "$XDG_CONFIG_HOME/polybar/launch.sh"
fi

if [ -x "$(command -v dunst)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/dunst"
    ln -si "$DOTFILES/dunst/dunstrc" "$XDG_CONFIG_HOME/dunst/dunstrc"
fi

if [ -x "$(command -v mpv)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/mpv/scripts"
    ln -si "$DOTFILES/mpv/scripts/mpris.so" "$XDG_CONFIG_HOME/mpv/scripts/mpris.so"
fi
