#!/bin/sh
ln -si $DOTFILES/profile ~/.profile

if [ -x "$(command -v vim)" ]; then
    ln -si $DOTFILES/vim/vimrc ~/.vimrc
fi

if [ -x "$(command -v zsh)" ]; then
    ln -si $DOTFILES/zsh/zshrc ~/.zshrc
fi

if [ -x "$(command -v tmux)" ]; then
    ln -si $DOTFILES/tmux/tmux.conf ~/.tmux.conf
fi

if [ -x "$(command -v git)" ]; then
    ln -si $DOTFILES/git/gitconfig ~/.gitconfig
    ln -si $DOTFILES/git/gitignore_global ~/.gitignore_global
fi

if [ -x "$(command -v Xorg)" ]; then
    ln -si $DOTFILES/xorg/xprofile ~/.xprofile
    ln -si $DOTFILES/xorg/Xresources ~/.Xresources
fi

if [ -x "$(command -v bspwm)" ]; then
    mkdir -p ~/.config/bspwm
    ln -si $DOTFILES/bspwm/bspwmrc ~/.config/bspwm/bspwmrc
fi

if [ -x "$(command -v sxhkd)" ]; then
    mkdir -p ~/.config/sxhkd
    ln -si $DOTFILES/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc
fi

if [ -x "$(command -v compton)" ]; then
    ln -si $DOTFILES/compton/compton.conf ~/.compton.conf
fi
