#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 50
bspc config border_width 5

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#878787"
bspc config focused_border_color "#8effff"
bspc config presel_feedback_color "#ffea35"

bspc rule --add Zathura state=tiled
