default_flags = "hi"

[[verbs]]
key = "ctrl-k"
internal = ":line_up"

[[verbs]]
key = "ctrl-j"
internal = ":line_down"

[[verbs]]
key = "ctrl-h"
internal = ":panel_left"

[[verbs]]
key = "ctrl-l"
internal = ":panel_right"

[[verbs]]
invocation = "edit"
shortcut = "e"
external = "$EDITOR {file}"
leave_broot = false

[[verbs]]
invocation = "lf"
external = "lf {file}"
