#!/bin/sh
URL=$(curl -fsSL https://api.github.com/repos/denoland/deno/releases/latest | grep download | grep "$(uname -s | tr '[:upper:]' '[:lower:]')" | sed 's/.*": "\(.*\)"/\1/')
cd "$DOTFILES/bin"
curl -L "$URL" -o deno.zip
unzip deno.zip
rm deno.zip
