#!/bin/sh
ln -si "$DOTFILES/profile" ~/.profile

if [ -x "$(command -v nvim)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/nvim/init.vim"
    ln -si "$DOTFILES/nvim/init.vim" "$XDG_CONFIG_HOME/nvim/init.vim"
fi

if [ -x "$(command -v zsh)" ]; then
    ln -si "$DOTFILES/zsh/zshrc" ~/.zshrc
fi

if [ -x "$(command -v tmux)" ]; then
    ln -si "$DOTFILES/tmux/tmux.conf" ~/.tmux.conf
fi

if [ -x "$(command -v git)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/git"
    ln -si "$DOTFILES/git/config" "$XDG_CONFIG_HOME/git/config"
    ln -si "$DOTFILES/git/ignore" "$XDG_CONFIG_HOME/git/ignore"
fi

if [ -x "$(command -v Xorg)" ]; then
    ln -si "$DOTFILES/xorg/xprofile" ~/.xprofile
    ln -si "$DOTFILES/xorg/Xresources" ~/.Xresources
fi

if [ -x "$(command -v bspwm)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/bspwm"
    ln -si "$DOTFILES/bspwm/bspwmrc" "$XDG_CONFIG_HOME/bspwm/bspwmrc"
fi

if [ -x "$(command -v sxhkd)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/sxhkd"
    ln -si "$DOTFILES/sxhkd/sxhkdrc" "$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
fi

if [ -x "$(command -v compton)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/compton"
    ln -si "$DOTFILES/compton/compton.conf" "$XDG_CONFIG_HOME/compton/compton.conf"
fi

if [ -x "$(command -v polybar)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/polybar"
    ln -si "$DOTFILES/polybar/config" "$XDG_CONFIG_HOME/polybar/config"
    ln -si "$DOTFILES/polybar/launch.sh" "$XDG_CONFIG_HOME/polybar/launch.sh"
    ln -si "$DOTFILES/polybar/playerctl.sh" "$XDG_CONFIG_HOME/polybar/playerctl.sh"
fi

if [ -x "$(command -v dunst)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/dunst"
    ln -si "$DOTFILES/dunst/dunstrc" "$XDG_CONFIG_HOME/dunst/dunstrc"
fi

if [ -x "$(command -v mpv)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/mpv/scripts"
    ln -si "$DOTFILES/mpv/scripts/mpris.so" "$XDG_CONFIG_HOME/mpv/scripts/mpris.so"
fi

if [ -x "$(command -v redshift)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/redshift"
    ln -si "$DOTFILES/redshift/redshift.conf" "$XDG_CONFIG_HOME/redshift/redshift.conf"
fi

if [ -x "$(command -v ranger)" ]; then
    mkdir -p "$XDG_CONFIG_HOME/ranger/plugins"
    ln -si "$DOTFILES/ranger/rc.conf" "$XDG_CONFIG_HOME/ranger/rc.conf"
    ln -si "$DOTFILES/ranger/plugins/autojump.py" "$XDG_CONFIG_HOME/ranger/plugins/autojump.py"
fi
