#!/bin/sh
[ -z "$DOTFILES" ] && echo "DOTFILES dir not set" && exit 1
base_url="https://github.com/mikefarah/yq/releases/download/2.3.0/yq_$(uname -s)_amd64"
target="$DOTFILES/bin/yq"
curl -L "$base_url" -o "$target"
chmod +x "$target"
