source ~/.zgen/zgen.zsh
if ! zgen saved; then
    zgen load romkatv/powerlevel10k powerlevel10k

    zgen load agkozak/zsh-z
    zgen load zsh-users/zsh-completions
    zgen load zsh-users/zsh-syntax-highlighting . feature/redrawhook
    zgen load kojandy/zsh-bd

    zgen save
fi

[ -z "$DOTFILES" ] && source "$HOME/.profile"

KEYTIMEOUT=1
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=$HOME/.zsh_history

setopt extended_history
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent
disable r

autoload -Uz edit-command-line
zle -N edit-command-line

bindkey -v
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward
bindkey '^U' push-line
bindkey '^?' backward-delete-char
bindkey -rM vicmd ':'
bindkey -M vicmd v edit-command-line

zmodload zsh/complist
bindkey -M menuselect h vi-backward-char
bindkey -M menuselect j vi-down-line-or-history
bindkey -M menuselect k vi-up-line-or-history
bindkey -M menuselect l vi-forward-char

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%F{yellow}%B* %d%b%f'

source "$DOTFILES/zsh/aliases.zsh"
source "$DOTFILES/zsh/p10k.zsh"

[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"
