source ~/.zgen/zgen.zsh
if ! zgen saved; then
    zgen oh-my-zsh

    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/vi-mode
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/autojump
    zgen oh-my-zsh plugins/docker
    zgen oh-my-zsh plugins/docker-compose

    zgen save
fi

stty -ixon
unsetopt AUTO_CD

KEYTIMEOUT=25

[ -z "$DOTFILES" ] && source ~/.profile

source $DOTFILES/zsh/aliases.zsh
source $DOTFILES/zsh/theme.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zshrc.local ] && source ~/.zshrc.local
