[ -z "$DOTFILES" ] && source "$HOME/.profile"

[ ! -d "$HOME/.zgen" ] && \
    git clone --depth 1 "https://github.com/tarjoilija/zgen.git" "$HOME/.zgen"
source "$HOME/.zgen/zgen.zsh"
if ! zgen saved; then
    zgen load romkatv/powerlevel10k powerlevel10k
    zgen load agkozak/zsh-z
    zgen load kojandy/zsh-bd
    zgen load zdharma-continuum/fast-syntax-highlighting
    [ ! -f "$HOME/.zgen/zdharma-continuum/fast-syntax-highlighting-master/current_theme.zsh" ] && \
        fast-theme clean

    zgen save
fi

KEYTIMEOUT=1
HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE="$HOME/.zsh_history"

[[ $- == *i* ]] && stty -ixon

setopt extended_history
setopt inc_append_history_time
setopt hist_find_no_dups
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent

disable r

autoload -Uz edit-command-line
zle -N edit-command-line

bindkey -v
bindkey -M viins "^A" vi-beginning-of-line
bindkey -M viins "^E" vi-end-of-line
bindkey -M viins '^P' history-search-backward
bindkey -M viins '^N' history-search-forward
bindkey -M viins '^K' push-line
bindkey -M viins '^?' backward-delete-char
bindkey -rM vicmd ':'
bindkey -M vicmd v edit-command-line

zmodload zsh/complist
bindkey -M menuselect h vi-backward-char
bindkey -M menuselect j vi-down-line-or-history
bindkey -M menuselect k vi-up-line-or-history
bindkey -M menuselect l vi-forward-char
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%F{yellow}%B* %d%b%f'

source "$DOTFILES/zsh/aliases.zsh"
source "$DOTFILES/zsh/p10k.zsh"

[ -f "$HOME/.zshrc.local" ] && source "$HOME/.zshrc.local"
