name: NVD Diff
run-name: 'Generate package diff with nvd'

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  nvd-diff:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_branch == 'bot/update-flake'
    strategy:
      matrix:
        include:
          - system: darwin
            runs-on: macos-latest
            target: .#darwinConfigurations.studio.system
            build-args: ''
            comment-title: 'Darwin Package Changes (studio)'
          - system: nix-on-droid
            runs-on: ubuntu-latest
            target: .#nixOnDroidConfigurations.default.activationPackage
            build-args: '--impure --extra-platforms aarch64-linux'
            qemu: true
            cachix-extra-pull: nix-on-droid
            comment-title: 'Nix-on-Droid Package Changes'
    runs-on: ${{ matrix.runs-on }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: docker/setup-qemu-action@v3
        if: matrix.qemu
        with:
          platforms: arm64
      - uses: nixbuild/nix-quick-install-action@v33
      - uses: cachix/cachix-action@v16
        with:
          name: kojandy
          extraPullNames: ${{ matrix.cachix-extra-pull || '' }}
      
      - name: Build old system and install nvd
        run: |
          git fetch origin master
          git checkout origin/master
          nix profile install nixpkgs#nvd
          nix build ${{ matrix.target }} ${{ matrix.build-args }} --out-link old-system
          git checkout ${{ github.event.workflow_run.head_sha }}
      
      - name: Build new system (cached from previous build)
        run: nix build ${{ matrix.target }} ${{ matrix.build-args }} --out-link new-system
      
      - name: Generate and comment nvd diff
        run: |
          nvd diff old-system new-system > nvd-diff.txt
          
          cat <<'EOF' > comment.md
          ## 📦 ${{ matrix.comment-title }}

          ```
          $(cat nvd-diff.txt)
          ```
          EOF
          
          gh pr comment ${{ github.event.workflow_run.pull_requests[0].number }} --body-file comment.md
        env:
          GH_TOKEN: ${{ github.token }}
