name: Update flake.lock
run-name: 'Check flake inputs for updates'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
      - uses: DeterminateSystems/update-flake-lock@da03c0f078bc4b2c37ee4f7e072d34bf8f188bb3 # v29
        with:
          token: ${{ secrets.PAT }}
          commit-msg: 'chore: update flake.lock'
          branch: bot/update-flake
          pr-title: 'chore: update flake.lock'
          pr-labels: automated
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
